name: Build, Deploy, and Generate Lighthouse Badges

on:
  push:
    branches:
      - main

jobs:
  build-deploy-badge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install build dependencies
      run: npm install

    - name: Run cache-busting script
      run: node cachebust.js

    - name: Check for build changes
      id: changes
      run: |
        git add -A
        git diff --cached --exit-code || echo "changes=true" >> $GITHUB_ENV

    - name: Commit and push build output
      if: env.changes == 'true'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "📦 build cache-busted output [skip ci]"
        git push

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: social-graph
        directory: build

    - name: Install Lighthouse and Badge Generator
      run: npm install -g lighthouse lighthouse-badges

    - name: Run Lighthouse and Generate Badges
      run: |
        lighthouse-badges \
          --url https://matt.berryman.social \
          --output-path badges


    - name: Commit and push badge updates
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add badges/
        git commit -m "📊 update Lighthouse badges [skip ci]" || echo "No badge changes to commit"
        git push
