name: Build, Deploy, and Generate Lighthouse Badges

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy-badge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Run cache-busting script
      run: node cachebust.js

    - name: Check for build changes
      id: build_changes
      run: |
        git add -A
        git diff --cached --exit-code || echo "BUILD_CHANGED=true" >> $GITHUB_ENV

    - name: Commit and push build output
      if: env.BUILD_CHANGED == 'true'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "📦 build cache-busted output [skip ci]"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: social-graph
        directory: build

    - name: Install Lighthouse and badge tools
      run: npm install -g lighthouse lighthouse-badges

    - name: Run Lighthouse and generate badges
      run: |
        lighthouse-badges \
          --url https://matt.berryman.social \
          --output-path badges 
          
    - name: Check for badge changes
      id: badge_changes
      run: |
        git add -A
        git diff --cached --exit-code || echo "BADGES_CHANGED=true" >> $GITHUB_ENV

    - name: Commit and push badge updates
      if: env.BADGES_CHANGED == 'true'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "📊 update Lighthouse badges [skip ci]"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
